---

- name: demo directory creation
  file:
    path: "/home/{{ ansible_user }}/{{ demo_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    setype: user_home_t
    mode: '0755'

- name: kickstart
  template:
    src: edge.ks.j2
    dest: "/home/{{ ansible_user }}/{{ demo_dir }}/edge.ks"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    setype: user_home_t
    mode: 0640

- name: tmp directory creation
  file:
    path: "{{ tmp_dir }}"
    state: directory
    owner: root
    group: root
    setype: tmp_t
    mode: '0755'
  become: yes

  